### ISSUE TITLE
More Ionic 3 resources

### ISSUE THREAD

**Issue by djabif** [Alexintosh/Awesome-Ionic#26]
Hi, thanks for this amazing list of resources.
I want to contribute with the following:

- Ionic 3 app for your Wordpress site using Wordpress REST API: https://ionicthemes.com/tutorials/about/ionic-wordpress-integration

- Ionic 3 app with a question and answer format (Q&A), similar to StackOverflow: https://ionicthemes.com/tutorials/about/building-a-complete-mobile-app-with-ionic-3

- Updated and complete tutorial about forms and validations in https://ionicthemes.com/tutorials/about/forms-and-validation-in-ionic

- Lots of tutorials in https://ionicthemes.com/tutorials. All the code from the tutorials is available for free.

**Comment by Alexintosh** [comment]
Please make a pull request :)

**Comment by djabif** [comment]
Will do! Thanks
